name: Test pipeline

on:
  #push:
  #  branches:
  #    - "**"
  # Runs triggered by pull requests are disabled to prevent executing potentially unsafe code from public pull requests
  # pull_request:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  job1:

    runs-on:
#      - windows-2019
      - macos-latest
    env:
      zlib_dir: C:\dep\zlib

    steps:

      - uses: actions/checkout@v2

      - name: Run a command
        run: |
          pwd
          mkdir aaa
          readlink -f aaa
          readlink -f bbb
