name: Build Probackup on Linux

on:
  push:
    branches:
      - "**"
  # Runs triggered by pull requests are disabled to prevent executing potentially unsafe code from public pull requests
  # pull_request:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build_versions:
        description: Build versions
        default: 10, 13, 14, 15
      test_mode:
        type: choice
        description: Test mode
        options:
        - BASIC
        - CATCHUP
        - FULL

jobs:

  build-linux:
    name: ${{ format('REL_{0}_STABLE', matrix.pg_version) }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
#        pg_version: [10, 13, 14, 15]
        pg_version: ${{ fromJSON(github.event.inputs.build_versions && format('[{0}]', github.event.inputs.build_versions) || '[10, 13, 14]') }}

    runs-on:
      - ubuntu-20.04

    env:
      PG_BRANCH: ${{ matrix.pg_version == 10 && ' ' || matrix.pg_version == 15 && 'master' || format('REL_{0}_STABLE', matrix.pg_version) }}

    steps:

      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          echo "PG_BRANCH=${PG_BRANCH}<<<"
          cd travis
          ./make_dockerfile.sh
          docker-compose build

