name: Test workflow

on:
  push:
    branches:
      - "**"
  # Runs triggered by pull requests are disabled to prevent executing potentially unsafe code from public pull requests
  # pull_request:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build_versions:
        description: Build versions
        default: 9.5, 10, 13, 14, 15
      test_mode:
        type: choice
        description: Test mode
        options:
        - BASIC
        - CATCHUP
        - FULL

jobs:
  testjob:
    name: ${{ format('pg_probackup ({0}, v{1})', 'ubuntu-22.04', aaa) }}
    runs-on:
      - ubuntu-latest
    steps:
      - name: Simple
        run: id
      - name: Echo
        run: echo ${{ runner.name }}

